.PHONY: clean All

All:
	@echo "----------Building project:[ Fifo - Debug ]----------"
	@cd "Fifo" && "$(MAKE)" -f  "Fifo.mk"
clean:
	@echo "----------Cleaning project:[ Fifo - Debug ]----------"
	@cd "Fifo" && "$(MAKE)" -f  "Fifo.mk" clean
