.PHONY: clean All

All:
	@echo "----------Building project:[ boot - Debug ]----------"
	@cd "boot" && "$(MAKE)" -f  "boot.mk"
clean:
	@echo "----------Cleaning project:[ boot - Debug ]----------"
	@cd "boot" && "$(MAKE)" -f  "boot.mk" clean
