.PHONY: clean All

All:
	@echo "----------Building project:[ Ring - Debug ]----------"
	@"$(MAKE)" -f  "Ring.mk"
clean:
	@echo "----------Cleaning project:[ Ring - Debug ]----------"
	@"$(MAKE)" -f  "Ring.mk" clean
