.PHONY: clean All

All:
	@echo "----------Building project:[ film_1 - Debug ]----------"
	@cd "film_1" && "$(MAKE)" -f  "film_1.mk"
clean:
	@echo "----------Cleaning project:[ film_1 - Debug ]----------"
	@cd "film_1" && "$(MAKE)" -f  "film_1.mk" clean
