.PHONY: clean All

All:
	@echo "----------Building project:[ Time - Debug ]----------"
	@cd "Time" && "$(MAKE)" -f  "Time.mk"
clean:
	@echo "----------Cleaning project:[ Time - Debug ]----------"
	@cd "Time" && "$(MAKE)" -f  "Time.mk" clean
