.PHONY: clean All

All:
	@echo "----------Building project:[ test_1 - Debug ]----------"
	@cd "test_1" && "$(MAKE)" -f  "test_1.mk"
clean:
	@echo "----------Cleaning project:[ test_1 - Debug ]----------"
	@cd "test_1" && "$(MAKE)" -f  "test_1.mk" clean
