.PHONY: clean All

All:
	@echo "----------Building project:[ progress - Debug ]----------"
	@cd "progress" && "$(MAKE)" -f  "progress.mk"
clean:
	@echo "----------Cleaning project:[ progress - Debug ]----------"
	@cd "progress" && "$(MAKE)" -f  "progress.mk" clean
